-- APP_USER
CREATE TABLE APP_USER (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    EMAIL VARCHAR(255) NULL,
    PASSWORD_HASH VARCHAR(255) NULL,
    DISPLAY_NAME VARCHAR(50) NULL,
    ACCOUNT_TYPE VARCHAR(30) NOT NULL DEFAULT 'REGISTERED',
    MERGED_INTO_USER_ID BIGINT NULL,
    MERGED_AT DATETIME NULL,
    LAST_ACTIVE_AT DATETIME NULL,
    GUEST_EXPIRES_AT DATETIME NULL,
    TIME_ZONE VARCHAR(50) NOT NULL DEFAULT 'Asia/Seoul',
    ROLE VARCHAR(30) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NULL,
    PRIMARY KEY (ID),
    CONSTRAINT UK_APP_USER_EMAIL UNIQUE (EMAIL)
);

-- PUSH_DEVICE_TOKEN
CREATE TABLE PUSH_DEVICE_TOKEN (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    OWNER_USER_ID BIGINT NOT NULL,
    PLATFORM VARCHAR(30) NOT NULL,
    DEVICE_TOKEN VARCHAR(512) NOT NULL,
    APP_VERSION VARCHAR(50) NULL,
    DEVICE_NAME VARCHAR(100) NULL,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    LAST_REGISTERED_AT DATETIME NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NULL,
    PRIMARY KEY (ID),
    CONSTRAINT UK_PUSH_DEVICE_TOKEN_OWNER_TOKEN UNIQUE (OWNER_USER_ID, DEVICE_TOKEN),
    CONSTRAINT FK_PUSH_DEVICE_TOKEN_OWNER FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER(ID)
);

CREATE INDEX IDX_PUSH_DEVICE_TOKEN_OWNER_ACTIVE
    ON PUSH_DEVICE_TOKEN (OWNER_USER_ID, ACTIVE, LAST_REGISTERED_AT);

-- PUSH_NOTIFICATION_HISTORY
CREATE TABLE PUSH_NOTIFICATION_HISTORY (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    OWNER_USER_ID BIGINT NOT NULL,
    PUSH_DEVICE_TOKEN_ID BIGINT NULL,
    SOURCE VARCHAR(30) NOT NULL,
    PROVIDER VARCHAR(30) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    TASK_ID BIGINT NULL,
    RECURRENCE_SERIES_ID BIGINT NULL,
    OCCURRENCE_DATE DATE NULL,
    NOTIFICATION_KEY VARCHAR(120) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR(160) NOT NULL,
    PROVIDER_MESSAGE_ID VARCHAR(160) NULL,
    ERROR_CODE VARCHAR(120) NULL,
    ERROR_MESSAGE VARCHAR(500) NULL,
    ATTEMPTED_AT DATETIME NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_PUSH_NOTIFICATION_HISTORY_OWNER FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER(ID),
    CONSTRAINT FK_PUSH_NOTIFICATION_HISTORY_TOKEN FOREIGN KEY (PUSH_DEVICE_TOKEN_ID) REFERENCES PUSH_DEVICE_TOKEN(ID)
);

CREATE INDEX IDX_PUSH_NOTIFICATION_HISTORY_OWNER_ATTEMPTED
    ON PUSH_NOTIFICATION_HISTORY (OWNER_USER_ID, ATTEMPTED_AT, ID);

CREATE INDEX IDX_PUSH_NOTIFICATION_HISTORY_OWNER_IDEMPOTENCY_STATUS
    ON PUSH_NOTIFICATION_HISTORY (OWNER_USER_ID, IDEMPOTENCY_KEY, STATUS);

-- PASSWORD_RESET_TOKEN
CREATE TABLE PASSWORD_RESET_TOKEN (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    TOKEN_HASH VARCHAR(64) NOT NULL,
    EXPIRES_AT DATETIME NOT NULL,
    USED_AT DATETIME NULL,
    CREATED_AT DATETIME NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT UK_PASSWORD_RESET_TOKEN_HASH UNIQUE (TOKEN_HASH),
    CONSTRAINT FK_PASSWORD_RESET_TOKEN_USER FOREIGN KEY (USER_ID) REFERENCES APP_USER(ID)
);

CREATE INDEX IDX_PASSWORD_RESET_EMAIL_CREATED
    ON PASSWORD_RESET_TOKEN (EMAIL, CREATED_AT);

CREATE INDEX IDX_PASSWORD_RESET_USER_EXPIRES
    ON PASSWORD_RESET_TOKEN (USER_ID, EXPIRES_AT);

-- IDEMPOTENCY_RECORD
CREATE TABLE IDEMPOTENCY_RECORD (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    SCOPE_KEY VARCHAR(120) NOT NULL,
    HTTP_METHOD VARCHAR(10) NOT NULL,
    REQUEST_PATH VARCHAR(300) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR(160) NOT NULL,
    REQUEST_HASH VARCHAR(64) NOT NULL,
    STATUS_CODE INT NOT NULL,
    CONTENT_TYPE VARCHAR(120) NULL,
    RESPONSE_BODY TEXT NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    EXPIRES_AT DATETIME NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT UK_IDEMPOTENCY_SCOPE_METHOD_PATH_KEY UNIQUE (SCOPE_KEY, HTTP_METHOD, REQUEST_PATH, IDEMPOTENCY_KEY)
);

CREATE INDEX IDX_IDEMPOTENCY_EXPIRES
    ON IDEMPOTENCY_RECORD (EXPIRES_AT);

-- REFRESH_TOKEN_SESSION
CREATE TABLE REFRESH_TOKEN_SESSION (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    FAMILY_ID VARCHAR(36) NOT NULL,
    TOKEN_HASH VARCHAR(64) NOT NULL,
    IDLE_EXPIRES_AT DATETIME NOT NULL,
    ABSOLUTE_EXPIRES_AT DATETIME NOT NULL,
    LAST_USED_AT DATETIME NULL,
    REPLACED_AT DATETIME NULL,
    REVOKED_AT DATETIME NULL,
    CREATED_AT DATETIME NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT UK_REFRESH_TOKEN_HASH UNIQUE (TOKEN_HASH),
    CONSTRAINT FK_REFRESH_TOKEN_SESSION_USER FOREIGN KEY (USER_ID) REFERENCES APP_USER(ID)
);

CREATE INDEX IDX_REFRESH_TOKEN_USER_ACTIVE
    ON REFRESH_TOKEN_SESSION (USER_ID, REVOKED_AT, IDLE_EXPIRES_AT);

CREATE INDEX IDX_REFRESH_TOKEN_FAMILY
    ON REFRESH_TOKEN_SESSION (FAMILY_ID);

-- D-DAY_GOAL
CREATE TABLE DDAY_GOAL (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(50) NOT NULL,
    TARGET_DATE DATE NOT NULL,
    OWNER_USER_ID BIGINT NULL,
    CREATED_BY_USER_ID BIGINT NULL,
    CREATED_AT DATETIME NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_DDAY_GOAL_OWNER_USER FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER(ID),
    CONSTRAINT FK_DDAY_GOAL_CREATED_BY_USER FOREIGN KEY (CREATED_BY_USER_ID) REFERENCES APP_USER(ID)
);

-- RECURRENCE_SERIES
CREATE TABLE RECURRENCE_SERIES (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    OWNER_USER_ID BIGINT NULL,
    CREATED_BY_USER_ID BIGINT NULL,
    FREQUENCY VARCHAR(30) NOT NULL,
    INTERVAL_VALUE INT NOT NULL DEFAULT 1,
    RRULE VARCHAR(500) NOT NULL,
    TIME_ZONE VARCHAR(50) NOT NULL,
    RECURRENCE_START_AT DATETIME NOT NULL,
    RECURRENCE_UNTIL DATE NULL,
    RECURRENCE_COUNT INT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_RECURRENCE_SERIES_OWNER_USER FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER(ID),
    CONSTRAINT FK_RECURRENCE_SERIES_CREATED_BY_USER FOREIGN KEY (CREATED_BY_USER_ID) REFERENCES APP_USER(ID)
);

-- TASK
CREATE TABLE TASK (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(255) NOT NULL,
    TYPE VARCHAR(30) NOT NULL DEFAULT 'SCHEDULE',
    START_AT DATETIME NULL,
    END_AT DATETIME NULL,
    ALL_DAY BOOLEAN NOT NULL DEFAULT FALSE,
    CATEGORY VARCHAR(255) NULL,
    NOTIFICATION_ENABLED BOOLEAN NOT NULL DEFAULT TRUE,
    NOTIFY_AT DATETIME NULL,
    DESCRIPTION VARCHAR(255) NULL,
    STATUS VARCHAR(30) NOT NULL DEFAULT 'INBOX',
    TARGET_DATE DATE NULL,
    COMPLETED_AT DATETIME NULL,
    CARRY_OVER_COUNT INT NOT NULL DEFAULT 0,
    DEFER_REASON VARCHAR(30) NULL,
    DDAY_GOAL_ID BIGINT NULL,
    RECURRENCE_SERIES_ID BIGINT NULL,
    OCCURRENCE_DATE DATE NULL,
    ORIGINAL_OCCURRENCE_DATE DATE NULL,
    RECURRENCE_EXCEPTION VARCHAR(30) NULL,
    OWNER_USER_ID BIGINT NULL,
    CREATED_BY_USER_ID BIGINT NULL,
    UPDATED_BY_USER_ID BIGINT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_TASK_DDAY_GOAL FOREIGN KEY (DDAY_GOAL_ID) REFERENCES DDAY_GOAL(ID),
    CONSTRAINT FK_TASK_RECURRENCE_SERIES FOREIGN KEY (RECURRENCE_SERIES_ID) REFERENCES RECURRENCE_SERIES(ID),
    CONSTRAINT FK_TASK_OWNER_USER FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER(ID),
    CONSTRAINT FK_TASK_CREATED_BY_USER FOREIGN KEY (CREATED_BY_USER_ID) REFERENCES APP_USER(ID),
    CONSTRAINT FK_TASK_UPDATED_BY_USER FOREIGN KEY (UPDATED_BY_USER_ID) REFERENCES APP_USER(ID)
);
