-- Refresh token session storage.
-- Apply manually to production DB after backup verification.

START TRANSACTION;

CREATE TABLE REFRESH_TOKEN_SESSION (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    FAMILY_ID VARCHAR(36) NOT NULL,
    TOKEN_HASH VARCHAR(64) NOT NULL,
    IDLE_EXPIRES_AT DATETIME NOT NULL,
    ABSOLUTE_EXPIRES_AT DATETIME NOT NULL,
    LAST_USED_AT DATETIME NULL,
    REPLACED_AT DATETIME NULL,
    REVOKED_AT DATETIME NULL,
    CREATED_AT DATETIME NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT UK_REFRESH_TOKEN_HASH UNIQUE (TOKEN_HASH),
    CONSTRAINT FK_REFRESH_TOKEN_SESSION_USER FOREIGN KEY (USER_ID) REFERENCES APP_USER(ID)
);

CREATE INDEX IDX_REFRESH_TOKEN_USER_ACTIVE
    ON REFRESH_TOKEN_SESSION (USER_ID, REVOKED_AT, IDLE_EXPIRES_AT);

CREATE INDEX IDX_REFRESH_TOKEN_FAMILY
    ON REFRESH_TOKEN_SESSION (FAMILY_ID);

COMMIT;
