CREATE TABLE RECURRENCE_SERIES (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    OWNER_USER_ID BIGINT NULL,
    FREQUENCY VARCHAR(30) NOT NULL,
    INTERVAL_VALUE INT NOT NULL DEFAULT 1,
    RRULE VARCHAR(500) NOT NULL,
    TIME_ZONE VARCHAR(50) NOT NULL,
    RECURRENCE_START_AT DATETIME NOT NULL,
    RECURRENCE_UNTIL DATE NULL,
    RECURRENCE_COUNT INT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_RECURRENCE_SERIES_OWNER_USER FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER(ID)
);

ALTER TABLE TASK
    ADD COLUMN RECURRENCE_SERIES_ID BIGINT NULL,
    ADD COLUMN OCCURRENCE_DATE DATE NULL,
    ADD COLUMN ORIGINAL_OCCURRENCE_DATE DATE NULL,
    ADD COLUMN RECURRENCE_EXCEPTION VARCHAR(30) NULL,
    ADD CONSTRAINT FK_TASK_RECURRENCE_SERIES FOREIGN KEY (RECURRENCE_SERIES_ID) REFERENCES RECURRENCE_SERIES(ID);
