-- Daily Plan 결과 summary가 계획 확정 시점의 focus Task 목록을 기준으로 계산되도록 snapshot을 보존한다.

CREATE TABLE DAILY_PLAN_INITIAL_FOCUS_TASK (
    DAILY_PLAN_ID BIGINT NOT NULL,
    FOCUS_ORDER INT NOT NULL,
    TASK_ID BIGINT NOT NULL,
    PRIMARY KEY (DAILY_PLAN_ID, FOCUS_ORDER),
    CONSTRAINT FK_DAILY_PLAN_INITIAL_FOCUS_PLAN FOREIGN KEY (DAILY_PLAN_ID) REFERENCES DAILY_PLAN(ID) ON DELETE CASCADE
);

CREATE INDEX IDX_DAILY_PLAN_INITIAL_FOCUS_TASK
    ON DAILY_PLAN_INITIAL_FOCUS_TASK (TASK_ID);
