-- Task별 알림 preference와 명시적 알림 예약 시각을 추가한다.
-- 기존 Task는 기존 동작을 유지하도록 알림 활성화 상태로 둔다.

ALTER TABLE TASK
    ADD COLUMN NOTIFICATION_ENABLED BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN NOTIFY_AT DATETIME NULL;

CREATE INDEX IDX_TASK_OWNER_NOTIFICATION_TIME
    ON TASK (OWNER_USER_ID, NOTIFICATION_ENABLED, NOTIFY_AT, START_AT);

CREATE INDEX IDX_TASK_WORKSPACE_NOTIFICATION_TIME
    ON TASK (WORKSPACE_ID, NOTIFICATION_ENABLED, NOTIFY_AT, START_AT);
