-- 개인 iCalendar 읽기 전용 feed token 저장소.
-- token 원본은 저장하지 않고 SHA-256 hash만 저장한다.

START TRANSACTION;

CREATE TABLE CALENDAR_FEED_TOKEN (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    OWNER_USER_ID BIGINT NOT NULL,
    SCOPE VARCHAR(30) NOT NULL DEFAULT 'PERSONAL',
    WORKSPACE_ID BIGINT NULL,
    TOKEN_HASH VARCHAR(64) NOT NULL,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT DATETIME NOT NULL,
    REVOKED_AT DATETIME NULL,
    PRIMARY KEY (ID),
    CONSTRAINT UK_CALENDAR_FEED_TOKEN_HASH UNIQUE (TOKEN_HASH),
    CONSTRAINT FK_CALENDAR_FEED_TOKEN_OWNER FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER(ID),
    CONSTRAINT FK_CALENDAR_FEED_TOKEN_WORKSPACE FOREIGN KEY (WORKSPACE_ID) REFERENCES SHARED_WORKSPACE(ID)
);

CREATE INDEX IDX_CALENDAR_FEED_TOKEN_OWNER_ACTIVE
    ON CALENDAR_FEED_TOKEN (OWNER_USER_ID, ACTIVE);

CREATE INDEX IDX_CALENDAR_FEED_TOKEN_WORKSPACE_ACTIVE
    ON CALENDAR_FEED_TOKEN (OWNER_USER_ID, WORKSPACE_ID, SCOPE, ACTIVE);

COMMIT;
