ALTER TABLE TASK
    ADD COLUMN CREATED_BY_USER_ID BIGINT NULL,
    ADD COLUMN UPDATED_BY_USER_ID BIGINT NULL,
    ADD CONSTRAINT FK_TASK_CREATED_BY_USER FOREIGN KEY (CREATED_BY_USER_ID) REFERENCES APP_USER(ID),
    ADD CONSTRAINT FK_TASK_UPDATED_BY_USER FOREIGN KEY (UPDATED_BY_USER_ID) REFERENCES APP_USER(ID);

ALTER TABLE DDAY_GOAL
    ADD COLUMN CREATED_BY_USER_ID BIGINT NULL,
    ADD CONSTRAINT FK_DDAY_GOAL_CREATED_BY_USER FOREIGN KEY (CREATED_BY_USER_ID) REFERENCES APP_USER(ID);

ALTER TABLE RECURRENCE_SERIES
    ADD COLUMN CREATED_BY_USER_ID BIGINT NULL,
    ADD CONSTRAINT FK_RECURRENCE_SERIES_CREATED_BY_USER FOREIGN KEY (CREATED_BY_USER_ID) REFERENCES APP_USER(ID);
