-- Password reset token table.
-- Apply manually to production DB after backup verification.

START TRANSACTION;

CREATE TABLE PASSWORD_RESET_TOKEN (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    TOKEN_HASH VARCHAR(64) NOT NULL,
    EXPIRES_AT DATETIME NOT NULL,
    USED_AT DATETIME NULL,
    CREATED_AT DATETIME NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT UK_PASSWORD_RESET_TOKEN_HASH UNIQUE (TOKEN_HASH),
    CONSTRAINT FK_PASSWORD_RESET_TOKEN_USER FOREIGN KEY (USER_ID) REFERENCES APP_USER(ID)
);

CREATE INDEX IDX_PASSWORD_RESET_EMAIL_CREATED
    ON PASSWORD_RESET_TOKEN (EMAIL, CREATED_AT);

CREATE INDEX IDX_PASSWORD_RESET_USER_EXPIRES
    ON PASSWORD_RESET_TOKEN (USER_ID, EXPIRES_AT);

COMMIT;
