CREATE TABLE SHARED_WORKSPACE (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(300) NULL,
    CREATED_BY_USER_ID BIGINT NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_SHARED_WORKSPACE_CREATED_BY_USER FOREIGN KEY (CREATED_BY_USER_ID) REFERENCES APP_USER(ID)
);

CREATE TABLE WORKSPACE_MEMBER (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    WORKSPACE_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    ROLE VARCHAR(30) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    INVITED_BY_USER_ID BIGINT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NULL,
    PRIMARY KEY (ID),
    CONSTRAINT UK_WORKSPACE_MEMBER_WORKSPACE_USER UNIQUE (WORKSPACE_ID, USER_ID),
    CONSTRAINT FK_WORKSPACE_MEMBER_WORKSPACE FOREIGN KEY (WORKSPACE_ID) REFERENCES SHARED_WORKSPACE(ID),
    CONSTRAINT FK_WORKSPACE_MEMBER_USER FOREIGN KEY (USER_ID) REFERENCES APP_USER(ID),
    CONSTRAINT FK_WORKSPACE_MEMBER_INVITED_BY_USER FOREIGN KEY (INVITED_BY_USER_ID) REFERENCES APP_USER(ID)
);

CREATE INDEX IDX_WORKSPACE_MEMBER_USER_STATUS ON WORKSPACE_MEMBER (USER_ID, STATUS);
CREATE INDEX IDX_WORKSPACE_MEMBER_WORKSPACE_STATUS ON WORKSPACE_MEMBER (WORKSPACE_ID, STATUS);
