START TRANSACTION;

ALTER TABLE APP_USER
    MODIFY COLUMN EMAIL VARCHAR(255) NULL,
    MODIFY COLUMN PASSWORD_HASH VARCHAR(255) NULL,
    MODIFY COLUMN DISPLAY_NAME VARCHAR(50) NULL,
    ADD COLUMN ACCOUNT_TYPE VARCHAR(30) NOT NULL DEFAULT 'REGISTERED',
    ADD COLUMN MERGED_INTO_USER_ID BIGINT NULL,
    ADD COLUMN MERGED_AT DATETIME NULL,
    ADD COLUMN LAST_ACTIVE_AT DATETIME NULL,
    ADD COLUMN GUEST_EXPIRES_AT DATETIME NULL;

UPDATE APP_USER
SET ACCOUNT_TYPE = 'REGISTERED'
WHERE ACCOUNT_TYPE IS NULL;

CREATE INDEX IDX_APP_USER_ACCOUNT_TYPE_EXPIRES
    ON APP_USER (ACCOUNT_TYPE, GUEST_EXPIRES_AT);

COMMIT;
