-- Idempotency replay storage.
-- Apply manually to production DB after backup verification.

START TRANSACTION;

CREATE TABLE IDEMPOTENCY_RECORD (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    SCOPE_KEY VARCHAR(120) NOT NULL,
    HTTP_METHOD VARCHAR(10) NOT NULL,
    REQUEST_PATH VARCHAR(300) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR(160) NOT NULL,
    REQUEST_HASH VARCHAR(64) NOT NULL,
    STATUS_CODE INT NOT NULL,
    CONTENT_TYPE VARCHAR(120) NULL,
    RESPONSE_BODY TEXT NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    EXPIRES_AT DATETIME NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT UK_IDEMPOTENCY_SCOPE_METHOD_PATH_KEY UNIQUE (SCOPE_KEY, HTTP_METHOD, REQUEST_PATH, IDEMPOTENCY_KEY)
);

CREATE INDEX IDX_IDEMPOTENCY_EXPIRES
    ON IDEMPOTENCY_RECORD (EXPIRES_AT);

COMMIT;
