-- 사용자별 일일 계획과 focus Task 순서를 저장한다.

CREATE TABLE DAILY_PLAN (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    OWNER_USER_ID BIGINT NOT NULL,
    PLAN_DATE DATE NOT NULL,
    STATUS VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    CONFIRMED_AT DATETIME NULL,
    CLOSED_AT DATETIME NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NULL,
    PRIMARY KEY (ID),
    CONSTRAINT UK_DAILY_PLAN_OWNER_DATE UNIQUE (OWNER_USER_ID, PLAN_DATE),
    CONSTRAINT FK_DAILY_PLAN_OWNER FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER(ID)
);

CREATE TABLE DAILY_PLAN_FOCUS_TASK (
    DAILY_PLAN_ID BIGINT NOT NULL,
    FOCUS_ORDER INT NOT NULL,
    TASK_ID BIGINT NOT NULL,
    PRIMARY KEY (DAILY_PLAN_ID, FOCUS_ORDER),
    CONSTRAINT FK_DAILY_PLAN_FOCUS_PLAN FOREIGN KEY (DAILY_PLAN_ID) REFERENCES DAILY_PLAN(ID) ON DELETE CASCADE
);

CREATE INDEX IDX_DAILY_PLAN_FOCUS_TASK
    ON DAILY_PLAN_FOCUS_TASK (TASK_ID);
