ALTER TABLE TASK
    ADD COLUMN SCOPE VARCHAR(30) NOT NULL DEFAULT 'PERSONAL',
    ADD COLUMN WORKSPACE_ID BIGINT NULL,
    ADD CONSTRAINT FK_TASK_WORKSPACE FOREIGN KEY (WORKSPACE_ID) REFERENCES SHARED_WORKSPACE(ID);

CREATE INDEX IDX_TASK_SCOPE_OWNER ON TASK (SCOPE, OWNER_USER_ID);
CREATE INDEX IDX_TASK_SCOPE_WORKSPACE ON TASK (SCOPE, WORKSPACE_ID);

ALTER TABLE DDAY_GOAL
    ADD COLUMN SCOPE VARCHAR(30) NOT NULL DEFAULT 'PERSONAL',
    ADD COLUMN WORKSPACE_ID BIGINT NULL,
    ADD CONSTRAINT FK_DDAY_GOAL_WORKSPACE FOREIGN KEY (WORKSPACE_ID) REFERENCES SHARED_WORKSPACE(ID);

CREATE INDEX IDX_DDAY_GOAL_SCOPE_OWNER ON DDAY_GOAL (SCOPE, OWNER_USER_ID);
CREATE INDEX IDX_DDAY_GOAL_SCOPE_WORKSPACE ON DDAY_GOAL (SCOPE, WORKSPACE_ID);

ALTER TABLE RECURRENCE_SERIES
    ADD COLUMN SCOPE VARCHAR(30) NOT NULL DEFAULT 'PERSONAL',
    ADD COLUMN WORKSPACE_ID BIGINT NULL,
    ADD CONSTRAINT FK_RECURRENCE_SERIES_WORKSPACE FOREIGN KEY (WORKSPACE_ID) REFERENCES SHARED_WORKSPACE(ID);

CREATE INDEX IDX_RECURRENCE_SERIES_SCOPE_OWNER ON RECURRENCE_SERIES (SCOPE, OWNER_USER_ID);
CREATE INDEX IDX_RECURRENCE_SERIES_SCOPE_WORKSPACE ON RECURRENCE_SERIES (SCOPE, WORKSPACE_ID);
