START TRANSACTION;

CREATE TABLE APP_USER (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    DISPLAY_NAME VARCHAR(50) NOT NULL,
    TIME_ZONE VARCHAR(50) NOT NULL DEFAULT 'Asia/Seoul',
    ROLE VARCHAR(30) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NULL,
    PRIMARY KEY (ID),
    CONSTRAINT UK_APP_USER_EMAIL UNIQUE (EMAIL)
);

ALTER TABLE DDAY_GOAL
    ADD COLUMN OWNER_USER_ID BIGINT NULL,
    ADD CONSTRAINT FK_DDAY_GOAL_OWNER_USER FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER(ID);

CREATE TABLE RECURRENCE_SERIES (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    OWNER_USER_ID BIGINT NULL,
    FREQUENCY VARCHAR(30) NOT NULL,
    INTERVAL_VALUE INT NOT NULL DEFAULT 1,
    RRULE VARCHAR(500) NOT NULL,
    TIME_ZONE VARCHAR(50) NOT NULL,
    RECURRENCE_START_AT DATETIME NOT NULL,
    RECURRENCE_UNTIL DATE NULL,
    RECURRENCE_COUNT INT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_RECURRENCE_SERIES_OWNER_USER FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER(ID)
);

ALTER TABLE TASK
    ADD COLUMN RECURRENCE_SERIES_ID BIGINT NULL,
    ADD COLUMN OCCURRENCE_DATE DATE NULL,
    ADD COLUMN ORIGINAL_OCCURRENCE_DATE DATE NULL,
    ADD COLUMN RECURRENCE_EXCEPTION VARCHAR(30) NULL,
    ADD COLUMN OWNER_USER_ID BIGINT NULL,
    ADD CONSTRAINT FK_TASK_RECURRENCE_SERIES FOREIGN KEY (RECURRENCE_SERIES_ID) REFERENCES RECURRENCE_SERIES(ID),
    ADD CONSTRAINT FK_TASK_OWNER_USER FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER(ID);

CREATE TABLE PUSH_DEVICE_TOKEN (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    OWNER_USER_ID BIGINT NOT NULL,
    PLATFORM VARCHAR(30) NOT NULL,
    DEVICE_TOKEN VARCHAR(512) NOT NULL,
    APP_VERSION VARCHAR(50) NULL,
    DEVICE_NAME VARCHAR(100) NULL,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    LAST_REGISTERED_AT DATETIME NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NULL,
    PRIMARY KEY (ID),
    CONSTRAINT UK_PUSH_DEVICE_TOKEN_OWNER_TOKEN UNIQUE (OWNER_USER_ID, DEVICE_TOKEN),
    CONSTRAINT FK_PUSH_DEVICE_TOKEN_OWNER FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER(ID)
);

CREATE INDEX IDX_PUSH_DEVICE_TOKEN_OWNER_ACTIVE
    ON PUSH_DEVICE_TOKEN (OWNER_USER_ID, ACTIVE, LAST_REGISTERED_AT);

CREATE TABLE PUSH_NOTIFICATION_HISTORY (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    OWNER_USER_ID BIGINT NOT NULL,
    PUSH_DEVICE_TOKEN_ID BIGINT NULL,
    SOURCE VARCHAR(30) NOT NULL,
    PROVIDER VARCHAR(30) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    TASK_ID BIGINT NULL,
    RECURRENCE_SERIES_ID BIGINT NULL,
    OCCURRENCE_DATE DATE NULL,
    NOTIFICATION_KEY VARCHAR(120) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR(160) NOT NULL,
    PROVIDER_MESSAGE_ID VARCHAR(160) NULL,
    ERROR_CODE VARCHAR(120) NULL,
    ERROR_MESSAGE VARCHAR(500) NULL,
    ATTEMPTED_AT DATETIME NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_PUSH_NOTIFICATION_HISTORY_OWNER FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER(ID),
    CONSTRAINT FK_PUSH_NOTIFICATION_HISTORY_TOKEN FOREIGN KEY (PUSH_DEVICE_TOKEN_ID) REFERENCES PUSH_DEVICE_TOKEN(ID)
);

CREATE INDEX IDX_PUSH_NOTIFICATION_HISTORY_OWNER_ATTEMPTED
    ON PUSH_NOTIFICATION_HISTORY (OWNER_USER_ID, ATTEMPTED_AT, ID);

CREATE INDEX IDX_PUSH_NOTIFICATION_HISTORY_OWNER_IDEMPOTENCY_STATUS
    ON PUSH_NOTIFICATION_HISTORY (OWNER_USER_ID, IDEMPOTENCY_KEY, STATUS);

COMMIT;
