CREATE TABLE TASK_TEMPLATE (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    OWNER_USER_ID BIGINT NULL,
    TITLE VARCHAR(30) NOT NULL,
    DESCRIPTION VARCHAR(300) NULL,
    TYPE VARCHAR(30) NOT NULL,
    CATEGORY VARCHAR(30) NULL,
    ALL_DAY BOOLEAN NOT NULL DEFAULT FALSE,
    DEFAULT_START_TIME TIME NULL,
    DEFAULT_DURATION_MINUTES INT NULL,
    RECURRENCE_FREQUENCY VARCHAR(30) NULL,
    RECURRENCE_INTERVAL INT NULL,
    RECURRENCE_BY_DAYS VARCHAR(100) NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_TASK_TEMPLATE_OWNER_USER FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER(ID)
);

CREATE INDEX IDX_TASK_TEMPLATE_OWNER_USER_ID ON TASK_TEMPLATE (OWNER_USER_ID);
