-- Task 아래 한 단계 checklist item을 저장한다.

CREATE TABLE TASK_CHECKLIST_ITEM (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    TASK_ID BIGINT NOT NULL,
    TITLE VARCHAR(30) NOT NULL,
    DONE BOOLEAN NOT NULL DEFAULT FALSE,
    SORT_ORDER INT NOT NULL,
    COMPLETED_AT DATETIME NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_TASK_CHECKLIST_ITEM_TASK FOREIGN KEY (TASK_ID) REFERENCES TASK(ID) ON DELETE CASCADE
);

CREATE INDEX IDX_TASK_CHECKLIST_ITEM_TASK_ORDER
    ON TASK_CHECKLIST_ITEM (TASK_ID, SORT_ORDER, ID);
